name: Update WarpKey Data

on:
  schedule:
    - cron: '0 */1 * * *'  # æ¯å°æ—¶è¿è¡Œä¸€æ¬¡
  workflow_dispatch:  # å…è®¸æ‰‹åŠ¨è§¦å‘

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23.5'

      - name: Build warpkey
        run: |
          go build -o warpkey-linux-amd64 main.go
          chmod +x warpkey-linux-amd64

      - name: Run warpkey to update data
        run: |
          ./warpkey-linux-amd64
          
      - name: Update timestamp in index.html
        run: |
          current_time=$(date +"%Y-%m-%d %H:%M:%S")
          # æ›´æ–°è‹±æ–‡ç‰ˆæœ¬çš„æ—¶é—´æˆ³
          sed -i "s/Keys are updated to GitHub daily at Every Hour\./Keys are updated to GitHub daily at Every Hour. Last update: $current_time\./g" index.html
          # æ›´æ–°ä¸­æ–‡ç‰ˆæœ¬çš„æ—¶é—´æˆ³
          sed -i "s/å¯†é’¥ä¼šæ¯ä¸ªå°æ—¶è‡ªåŠ¨pushåˆ°æœ¬ä»“åº“ä¸­,ä½ å¯ä»¥é€šè¿‡æœ¬ç«™è·å–/å¯†é’¥ä¼šæ¯ä¸ªå°æ—¶è‡ªåŠ¨pushåˆ°æœ¬ä»“åº“ä¸­,ä½ å¯ä»¥é€šè¿‡æœ¬ç«™è·å–ã€‚æœ€åæ›´æ–°: $current_time/g" index.html

      - name: Commit and push if there are changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          if git status --porcelain | grep -q '^'; then
            current_time=$(date +"%Y-%m-%d %H:%M:%S")
            git add ./data index.html
            git commit -m "ğŸš€Automatic update - $current_time"
            git push
          else
            echo "No changes to commit"
          fi